apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  interval: 12h
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 12h
  chart:
    spec:
      version: "0.4.x"
      chart: plex-media-server
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
  values:
    image:
      registry: quay.io
      repository: linuxserver.io/plex
      tag: arm64v8-latest
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      ingressClassName: tailscale
      url: plex.${TSNET}
      annotations:
        tailscale.com/funnel: "true"
    rclone:
      enabled: true
      image:
        registry: index.docker.io
        repository: rclone/rclone
        tag: 1.62.2
        pullPolicy: IfNotPresent
      configSecret: rclone-plex-secret
      remotes:
        - r2:movies
      readOnly: false
