apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bluesky-pds
spec:
  interval: 1h
  url: https://charts.nerkho.ch
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bluesky-pds
spec:
  interval: 1h
  chart:
    spec:
      chart: bluesky-pds
      version: 0.2.x
      sourceRef:
        kind: HelmRepository
        name: bluesky-pds
  values:
    image:
      tag: 0.4.74
    pds:
      config:
        hostname: pds.0xf.fr
        secrets:
          existingSecret: bluesky-pds-secrets
        pdsEmailFromAddress: "netop@0xf.fr"
      dataStorage:
        size: 10Gi
        mountPath: /pds
        storageClass: local-path
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: "letsencrypt"
      hosts:
        - host: "*.pds.0xf.fr"
          paths:
            - path: /
              pathType: Prefix
        - host: "pds.0xf.fr"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: pds-0xf-fr-tls
          hosts:
            - "*.pds.0xf.fr"
            - "pds.0xf.fr"
