apiVersion: v1
kind: Secret
metadata:
    name: tailscale-config
    namespace: tailscale
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:K81tCubslOIOMi8fQ0iQ6aLTiJwGcQ5QO8OWhBorZg6naDk+HroWXc4/DscIM9KI2PulptmPlEX5wfIhFEiEJ2x9Rkug3UMA6WvD5S1I3lmazVXfibRa3aWeCoWpSq04TVczNLnD2IxABZmxs3sjybjAA+dQwwbW0rVIrQXn9Lj5n8WiDObvHNxTcy4fSaxHQWcAs4tU9KbIPrg=,iv:5qQf7JrW0iEw/BAyXxL7xbOLIXrVlehhuEuHIyLBlJs=,tag:4hnjNZY2Lh4rDzg/m87WKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWnBTQm8xVjZMNWU1bDBM
            Rkp1T0RyZklheDFNQ2NYZWR0QVZrK0t5TXlvCnNOK2JhVTNhRnRrTG1iQkJIdU5k
            b1gvZFFzTHgvZHh1ZEJISWhlYXRycTAKLS0tIHh6MW9wZHFybllyVTd0ZUF1MTRW
            RDE2SDF6YSthcGhlTnQxY0gxbmR0ZlkKv9+yN/2uJBzIvMRpL19+nCVWgL7boKer
            Y1JflGPaFLuV/JQovix7+NRCmjqVVBG3/HmfphSfkKeHAVUXEmkSuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eUlMbkRQYlUvZlRJNldP
            L2J0Z2J5UytvQU1GWDNJK2h5alhWa3laMUU4Ckd4NldGckpvRUdCdFM1RU5LNitr
            VHRJWVdBQ0paMEZ6bTM2Nlc1bkNvb00KLS0tIDl5U0FWT0NuQWZYNWI3WUQ4L3R0
            b2lSaEhPU08yemhKbHM2VU5paXBLQzgKE6sKg8ANH9ulZ0QTLFHNZzKDcGIDwU1Z
            p4TvkTX/yxOgfvA/AQR7evrMdNAefq7SwIDa5XRH1w0p3fCC6/9m3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T15:50:54Z"
    mac: ENC[AES256_GCM,data:vvqanvA8Xb5svi4TpJtUwX4U7at2WussoVNIvY2gxXVlwlnxGRgMBb4JxbkBTPWgt7jEYwQdgl39jfANu3BxfFcQm2wrN3UERETz87rtAmTB8Lov71iXlyJm75Lgd8bJHRxmk96VLShpP7/rwt7K7DLg6WhI8M1q/LZ5avkvkXQ=,iv:WVBm3dpQiWdIPGiBxQDgEUmjFQTfukC9FHddEMKnm+8=,tag:4pj6s5lCQ1kn1PzG1/s8XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
