apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kolaente
  namespace: flux-system
spec:
  interval: 12h
  url: https://kolaente.dev/api/packages/vikunja/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
  namespace: vikunja
spec:
  interval: 12h
  chart:
    spec:
      chart: vikunja
      sourceRef:
        kind: HelmRepository
        name: kolaente
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: helm-config
