apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 5m
  path: "./releases"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cnpg
    namespace: flux-system
  targetNamespace: cnpg-system
  wait: true
  timeout: 5m
