apiVersion: v1
kind: Secret
metadata:
    name: csi-s3-secret
type: Opaque
stringData:
    accessKeyID: ENC[AES256_GCM,data:JURr2Dhk/qvlha8Mfj77WM38fps741WKSQ==,iv:UFr7lHF7QNQM/r2rOyZ7aNxASrCL6WN0+buSydIlClg=,tag:pxklJQdwcyMQ0UqqHUuXmQ==,type:str]
    endpoint: ENC[AES256_GCM,data:gHqjBtmyyRAbhcgLKjczGuMWc0CJ50c2ftg8hQbfl/rKYNqCDwvkXR0=,iv:QigrpFHJRqZKOAKOopzYUYRvrzfpXCrZt8WYJvPnkYA=,tag:bf6Hzbn9XPH1At5EKwpOgQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:HqPqnlR2j7I5T1nYGJj4UYAbR0BEnXRyaxip9c+D8Q==,iv:/JvkHy9SuhTaMAIakb8SzcMx4vycT4MVzeDssOdlk8o=,tag:4qSUP+vL4+fctzTQwN9g5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TGg1NVZRNUdLMkNvNGs0
            OUdOUnNYd2E2VWxFUEV0aFkvb2JEN0VXbGk4Ckpjc2lPMW8rMEViWm9Eb1BmNjUx
            MmtsaGNhODZDMGpYRE4zQnlzSnFkczQKLS0tIDRhQzR5eWppaFJzeWJIYWJEc041
            VElRYVNyOXhkOXRwUzVSYW95ak1vcG8KaAzrMgwIlZN5HMD6wkPCHLFgA/eRF7MK
            L9/MYi9Yi5h6APb3kmfwfjKc51M11/TRWgz/VuhLfzpY79G6KaRVTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UVlwVnVTSmVBMDZSUDZK
            MmhDZDdWV2FQRkdNY1EyYVo1cjBGWUdCV3dJCk5oOXFrMzZIeU5VZ1BXN3UwNU00
            aG84T2NKRUtRem1LNldSdXl6WEdFUkkKLS0tIDk1SVpPTGx4ckxUUlBIbVlhZDBj
            clM3SjJPNkppZG5NeXFvRWlDQldLMmcKLq9unRct5EwEhCjA6++y4zgGscCdIMvt
            ef/d6kc1yBJZmTfmJ5DN4tgJ8bmhePmi1F27PFhR4WvMYpijF49HVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g4q5q0lytudrnvvmdgxnlhwu37lak0qgk8kf4dahg4md87wj0ytq2l2xuc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVnRRUWpGSVp5RldNWElD
            SDdteTFqV0JIL3R6RG5xTi8vLzZlajYzTDB3Ck9zVzEzQkxKamplL01yWkNjNC9B
            akJvQTMyWlNmN1QwRENhSncxN3M1YmsKLS0tIDAyOFNLd2dJQ3lBUnF6UnBKY05q
            cCtaUUwvRWVQY2tKVWNubHBGMk0reUUKGhTMSuw8E5BI3btmGEWVibGwHLnOHlBQ
            MRxguJe7eZ3AKBLxO25ivLJ+vY0CMRMrGWG5dnDsVqD++UfFzUZcnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-28T09:07:36Z"
    mac: ENC[AES256_GCM,data:f/NwraDcI4BrZYly0wzuTC5vOt4gS1+gwT463QE6Xyq6l1zfbMan9kCuE/FQ14/afbwTw2SibeSMKbRIUF7XKqVmGTHNrtYLPNU6mIFK4uin+X4thGfjd/zJPSduqOyo/l1fzQ65aCWkdZ2voFNf7kLALkWtgkqej+hV/rL4KnA=,iv:Ujw+qbmjSo3pnTWM5pn5kAKtMoFRAzlpJ2C8DGkmPqg=,tag:jH37Z1ZfxUmds5ln0ympZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
