apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:kBORbaIcNWoBp8RIS9Op1gCEzdaexEPICZ7ETqVr+U4sy3kDklxd6Q==,iv:ZRKN8q1gMF6PfEnHVBNdDbzqamsG3mpXA0RAm8E+qXA=,tag:kyfWdjaa2f7Ih9/88eysKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTWZtV0Q5azljNlA5dE5I
            U2UvUXJBNFgrSHNlR3NPaDNET0QyZ05uYTBrCjhhWTNleEZzeFhyTEFVeklydklI
            R0wvRUEyWlhHREFlckM0NVRRblg2RncKLS0tIFNNU2xoWWZrc0E5MnI5UVhCUi9G
            aGNCdmxyT2dJVmRLSVVEcW1VdDhrV0kKqlun5UnTGNqUoalse1s7mRi7+vuxLB/B
            ELJj1lA9lMJKZdwdfHbptV9leKHL5uSJShI8wygTIRejvVHTeUObFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodUUvZWNrQVRpZTFtM3JO
            cHlzMCtjN0ZrNmVpMDZZYzNmQU9hZ0xUZUMwCkY1UHl3Vm13ZFBBc0RoaG9rVTcw
            WStDcENQbUV5SnJxRXorSnZYcURQRk0KLS0tIHJjUEFWUVBSYjUrZlY2djV6ZFFP
            S0p3dlZ0a3REcXVQV3ovdjlDMlpaVXcKH/6gweuXazW02VnKWwq8uzIj7NEBvecv
            b5+dh4noW9jl1LjFBkmz9YoyNvn+YU5zo0fH9Krda8RFjABx629W/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g4q5q0lytudrnvvmdgxnlhwu37lak0qgk8kf4dahg4md87wj0ytq2l2xuc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUzNKRnlKMk5mdnpqTzZk
            aGdJQ2ZYSnh5Q05EZDVBYlh6NFBEZFpueEF3CkNLVW80NmZiZDI4MEN2QmxZMlMr
            WXJBcDdZZDRGblV5cjFnYVlXNG1GZm8KLS0tIGtpTkFiNXBCM3diNFlQY1JWRmc2
            c21DQkhBNW1rRFhpcVJwZVpSTUZLRWMK+f+ok8DeesLFQKoQDzt60g4NtascyiQv
            0AjiOAMBAJclwgBNoBJz92SQgtC/HwmO2rsWzktuWKzimCTcC1tcYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T21:32:55Z"
    mac: ENC[AES256_GCM,data:sXeWWzu6RpdMGbvBcDLJ+aU3m+3uyrkuRDrGOQKmx+r7FqkHpO4Gvhdx/98ssswooaIAEXhG7i525YTQMqAJcOI6t+sPKOlfqpyo93GRWbZyMLdT2beEtD2e+Bv9dFt6SAPB4rfrEy1i5MaqiVaP8elifgcxcp6f4loQNDImrIs=,iv:JNL7klDU3gxMjtPF7vHKS97dszotMHFbJaVC2KtSIZY=,tag:D4zmSr12dHj81OeEq4XOfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
