apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: damoun
  namespace: flux-system
spec:
  interval: 12h
  url: https://charts.damoun.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: transmission
  namespace: transmission
spec:
  interval: 12h
  chart:
    spec:
      chart: transmission
      sourceRef:
        kind: HelmRepository
        name: damoun
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: helm-config
