apiVersion: v1
kind: Secret
metadata:
    name: hermes
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:UH7ZQ7uJFu8Dwp0Lfnr/DoMSYwkYqoV3EIiO340/+EvXKYMBZOgv7lYlYA34s8ypSqs6Ll4iHtDZc/1BMH1glg==,iv:5PE3CD8+eNGfMXpRj+iPoSNfjRFclPKjnkFd9N/qf2Y=,tag:TAMLWPAJmY2on3X7sFmusQ==,type:str]
    EXA_API_KEY: ENC[AES256_GCM,data:VoD71pE+cCkuMdXLDC5vOAbnRrKkSaxXiV9F/4KOWzXRkbac,iv:q8uCHQeDzMPenmu3Mx9VJfaxm7sSUkd7eNPKAp/kuII=,tag:oa73VyTi+SvndYqC8IxTGg==,type:str]
    DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:qEKDbVytUeIU5n8lfUQoTIUf,iv:NzsrLWXNu90UAihDFic0JIgm+AZZAXVJXsVch/SmuMU=,tag:bRf7FmiyG9MC5BwjlwCB4A==,type:str]
    DISCORD_HOME_CHANNEL: ENC[AES256_GCM,data:CQsbzuVTOxM/8uaUiT8teZTEIg==,iv:/NgsPoPbcBaWTSZ8dLfS7ihIIXcLEHlEqV7oKhSzQpY=,tag:R9GFpVkltuCR5Oc7xCH93g==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:ICnOC7EoewGv2uPxw6EEo7oRF3ugZgS42WJV56HD5ToV0BEzP/tO/J72DbAfbCIgGpLc+M6ieCx8AzEW3rn6cJ41XTJOxqmw,iv:L1Rcde6Hu6rWuifhZOYkxy7Levyqam9C9Jj1UU2ZASg=,tag:QDrZivFT3kON63z/96Al7A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWDRnblNsSSs4SzdqYTBB
            cnNobTFHWFlReVhGYVR6YkR5MDZTK2tKOFNBCjlLeXc5SlVtMnYxa3ZXMUVsdlBK
            OHhzeEVwczliRmVxbDAvQk1HNFZVNTgKLS0tIGRIdEdsU1JFVzZHSzhSSG4rV0lW
            azZ6YTdPaDNlVEhjU1o0cDV0b3N3NGcK79MJ61KecYUJoTGNy8DwwjHdfJoKUL3a
            /MAs33UCJJRelXgnRv4p2lFUJYZW1iYXf7SlDIijWcMQWi95Rg26Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZjViUDI2Q2MxdzQ3THlG
            d0owaVJSYU9mQWlXMCt1WVkzT2hsNGt4OUdnCkJCOVhpU0cwUC9jZlhoa1BEa0w1
            WldNQWZDTndKKzlhUkd6T3k2SG56M1EKLS0tIGNIbjJ0SjJXV1NrTXFjN291Q3A3
            LzVQakFvU2tiei91dCtidlFUN2FBS0UKqYaGNjnpLr2DgxQQ42Kd8TUWkutyauhf
            Cwl2zZJpcG2B2nYg9CtXiDpsKLfv0CEZOxnWv563HjVF6a9ebKS2lA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNE9hOThCbjhUSlZSS2I0
            VU5mZ01WWE12cXNrb0QwSFhrdXNVWGtmU1JFCmJRTkIrZE5LeTYrRExyaUxZZHRE
            c09Ya2NoMzZMTjJPOFQ2dEtRTktRMU0KLS0tIDkramQ5UG1teE12QkhxV3luL2FB
            YURFdlBGSi9KK3c2Vkg5WVBhVWp3MlEKp41gZ4ByzqiofWiG+lIGl09E444SADsO
            a65vwo8cn87LC0KbieTZ3q8t04oatnSBtyLnmXCe5bMNWolGzFt6rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4q5q0lytudrnvvmdgxnlhwu37lak0qgk8kf4dahg4md87wj0ytq2l2xuc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T17:11:15Z"
    mac: ENC[AES256_GCM,data:EFFkXJlE0iE4G/UYekIsp+GG8Lu7aGv2N8R1fe6AsNgosU/aebqDeICr9yE5EfX4tKnVRHEJMJFSdEfOaEJ3xUyhA9UECElZbtbAx0QsfZKztc2fzqOZzWynbn25+6dJcc5FEAe6W9qA2OzJPXPgBewObUyTcLVG6FhSo83XMLw=,iv:WXfgvyR7I3c5JRYbB5D1HP+42b7/G/yDEfMv3H02PqQ=,tag:A3xXx8jNN4B4/5Cb3U5KTw==,type:str]
    version: 3.13.1
