apiVersion: v1
kind: Secret
metadata:
    name: alloy-env
    namespace: alloy
stringData:
    GRAFANA_CLOUD_TOKEN: ENC[AES256_GCM,data:P4KkdZTdclYthJBdohRt3aVvQMInKaOEGKCTlHXAyJxRkofMQl2YAnR4rzzYlvd+2DF3PP4tZCugoh+lhDBAaW4k2DRF4jD/erTJqXb+eSjxvRkS1jgJRXW7aeZVjWAQOOsi6wblWay1x/iLDwsqQWkhoach8UdcLdUxyVlXaxQ=,iv:woDLSrZJHBeEeg2EqXktQdzw0hdfGnsl2eOko/8gMC0=,tag:ve0/wSh7kAkOghqneBbrXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY3ZvZitrWHlZTzQ2V09T
            UE1zY3M3c1RxWk9TVnB4Mk0xWDBZQm53UWxBCkUzNWJDSmt4MTZVRS96TWlMUm9t
            KzhUcHZiMjdKUjlNd2dJR1NJZkQrOHMKLS0tIHh4M2NWRHpsVFVZZ2tBdW5mVTBS
            VmFLdDd4K0hPY2xCbUlmTE92TUNwNzAKLQg8nPWvRybwARmrArnrSVsIDPB6tgA7
            fHpIiiy2VyXFZEW6kYynYBef6ZfEhLOZovXQEjcor2GEahO/V4Bruw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQkQ4c0VXcDM4L0NlVmsx
            ZVBvb3kvL29Ic2h2Y1hmTG9uY2hqM3JCMndrCjVpNkdZUWFUZjVodnB1ektjdlZF
            aEo4SG5lbVhEZWdmM0lkcDQ1VnorUHMKLS0tIFhtY29DRkVSL0JGY3IzVkxObjlx
            UXIzL2ZyN3lFMG0vWjR1UEhYTm4rWTgK/TDGWHGRWGuF+WrjSduaKNU3jqHHzDWw
            crd8P3bvmr6PhP5iU2Qyr5uorC29XUmBxVGkqrY+6dGNLFBfNuRybw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbVdsaytySEhmU05oRGlP
            Y0hlMjJKakgvYzYveThncnFuaEcxUmw2K3ljCkhqUXRsenJVbXhDSENibkVQYkNa
            cWdtUlFteVB0bTN1RnpnempyQkFXdncKLS0tIE0xTGlVTUhUcW9ablBIVi9WZnl2
            bDlkOUJUNUU3Q0FrSlNtU2NkWWQ2MDQKwqXURXDxWaU9NcPysBgmrroCS8rS92OD
            zFjABzpSLAvs+R4IAvLwzlct1RgyX63brRKQAUDeenw2vCaJX3IUSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4q5q0lytudrnvvmdgxnlhwu37lak0qgk8kf4dahg4md87wj0ytq2l2xuc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T18:23:48Z"
    mac: ENC[AES256_GCM,data:VBZLBlWBVZnGx6xwNWnog/YzXySRglHZFvZByYD6L9Pvm+tGk5Qm+xs7PV91vSZ9NYS1gqDpNUchYEgMP4N7Z/eRuKDspEzdx2KBaq0ROU6SwwKbrEzkGuiYuqKl717Yf494V2YtFZ8cZ//QKuqsdzmYzohlUW+lD715/qdttV4=,iv:wvDB2s2ARkTvnRrhyW04Z4lqbEFbKFqtjf7lbwKJ5g8=,tag:V5O/HCmakJks+4uKlheMlw==,type:str]
    version: 3.13.3
