apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
spec:
  serviceName: "api"
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/karitham/waifubot:main
          imagePullPolicy: Always
          command: [/bin/api]
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - secretRef:
                name: bot-env
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080
