apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: access
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - waifubot.${TSNET}
      secretName: waifubot-tls-secret
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bot
                port:
                  number: 8080
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080
