resources:
  - secret.yaml
  - waifubot.yaml
  - objectstore.yaml
  - pg.yaml
  - ingress.yaml
  - image-upgrader.yaml
images:
  - name: ghcr.io/karitham/waifubot
    newTag: v1.4.5 # {"$imagepolicy": "waifubot:waifubot:tag"}
