apiVersion: v1
kind: Secret
metadata:
    name: bot-env
type: Opaque
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:kG1stT4T0HNuCVuu7uTmqy28EeX8Ce9EV2R9V5DIyTew8jgHRnFqgLXhR1K8xu9DU34xGkA9p3ntYq8=,iv:HrhqI33Oz/ivXAS/VQVBy/xTf1kWY9tfYG3UKVy8rOY=,tag:J6DjT+1BSgFJ0w9g+9kv9Q==,type:str]
    APP_ID: ENC[AES256_GCM,data:yD/xgVfftECIl3Nx4bt90LXC,iv:BhDmsCETnSaY4i3VGQ/fWIaTZyt0R4br/79C4/aBR8E=,tag:Er80YW/SRciQF//auO2zVQ==,type:str]
    PUBLIC_KEY: ENC[AES256_GCM,data:fgR2x4e1L1/TuJgzRlBM2xlu4T++HfZX5FxPmTPQUynYcTfYccGr9UQjU4+aXuf8KXR7e4bVwHx6Xja2CNp1Kg==,iv:vvr3tr4yNBuelxmgB2mE9rxWqPkLGuIKtxkABu0bPz0=,tag:j39S1igt5+j73UKXye3REQ==,type:str]
    DB_URL: ENC[AES256_GCM,data:Rc0SwAlsCNV6T6nEKeYiXaVZijEx2gF7bh8iILroYhvh+24G+NKEeUHW99AsxdpJ1M9Ow853rKu43YmvhkXpzs8QFntQNnGardcbSrFOqbcTHyJrP+CQy/sITkIr0exwhQBr0nX3mPWu8AVKam1VBsoyn1PXtaJzj2rD2eQ=,iv:eicDaITEI+/EG2IUKBNhZ+9dm1d538UyDm1LstvExEM=,tag:M2oE+F7JMvsmn69jFmGsmw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:rmuUPy1TZSK9qz33EmUQD/f6BkFv7STVYfD1QN5zlJUifVlCjqlYkex2YDeQUDnSzJzBBQincuuGzu+WK92pV1mLWRG0mbwJ9ir3BDRB/o3Npoc5OVb8ZA==,iv:l0S3W/fHp2mKQk4xSx2XP+JK57so4fFzvmJLvfE7fMs=,tag:e4b+jonn/iBu0p1Uw+civA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZa0ZxYUVkLzJEVFg4WEYw
            TG5EK2tFZ3Z1bWhkR24zVGl0cG9KWXExTWhRCk5SNlNrTGVOeTZXUHlSNlNxS0Q2
            Q09kbDlzZzY0bStVS3A2SThEZFN3bVkKLS0tIG5selFuVEJTUVdvWm56aS92R283
            S0JndVdpUnVvK25Wa2VjMVNUdzg2aXcKDjq/7bM0sP+uH2j5XDFZIqwQ49VwZdfx
            28VDaLYfgghfn+eW9LzzhXqpAuUN5wpeUjqLTrmm1a3CUW0Cqb9QFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0gyKzBFT1laM0pzcWJG
            V2JSemsybXZlaHBKZmRmeFpGdEFhS2FmNEYwCmZvWFl2VmNJaHRhR2IxajdHdmd3
            VU51dVNRTFp2cTIySUN6ekJXaDdKa2MKLS0tIG01cjIyU05yNXhUV2hvWFNMODYv
            NDU3OXdHOENIOEJET0xLOEFsRWJRL2sKSG8+t/QRPufg7eYfp2YT5oOXZ/aIMnCY
            0De8xiF6KaLYCA5kPihHa0TEcVXrnjuCZhEM61GPYoKt5GgdhAy4dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T20:48:04Z"
    mac: ENC[AES256_GCM,data:0/9FgUjFE6NPGY7JFXyYYYOv4J7lVFg0N0hvKt17PWiHo+rGxJDXo8Rc8KnChLmbBTC71KA1EGxbOTR6w0NKHFl+3Zr/SGmvR+BZ+UVmCBkJdvr2SikdXcr8EBiH1SYeMFQAgm8kLFO/qcZFaR2xjBZTRnTiWBny+lkJIv6WKyM=,iv:YeeYSOlSUQk9WO4NmjKcfezbRXiePqnIbuGxJjtajFU=,tag:PTbDaO3882BofBkvOJJEQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
