apiVersion: v1
kind: Secret
metadata:
    name: bot-env
type: Opaque
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:kG1stT4T0HNuCVuu7uTmqy28EeX8Ce9EV2R9V5DIyTew8jgHRnFqgLXhR1K8xu9DU34xGkA9p3ntYq8=,iv:HrhqI33Oz/ivXAS/VQVBy/xTf1kWY9tfYG3UKVy8rOY=,tag:J6DjT+1BSgFJ0w9g+9kv9Q==,type:str]
    APP_ID: ENC[AES256_GCM,data:yD/xgVfftECIl3Nx4bt90LXC,iv:BhDmsCETnSaY4i3VGQ/fWIaTZyt0R4br/79C4/aBR8E=,tag:Er80YW/SRciQF//auO2zVQ==,type:str]
    PUBLIC_KEY: ENC[AES256_GCM,data:fgR2x4e1L1/TuJgzRlBM2xlu4T++HfZX5FxPmTPQUynYcTfYccGr9UQjU4+aXuf8KXR7e4bVwHx6Xja2CNp1Kg==,iv:vvr3tr4yNBuelxmgB2mE9rxWqPkLGuIKtxkABu0bPz0=,tag:j39S1igt5+j73UKXye3REQ==,type:str]
    DB_URL: ENC[AES256_GCM,data:J+rKlLkgPbS314CafdJP0/v91lAS14FuhhvkUtPl5KGu5mNfClQxcIw+XqCb12Y/AGTos+P4aK9z8N0NYlEL8NRO6LQoGCrwClE=,iv:E8e0QeaxY+7PS3lka4CGOp9myzrINzLDIAdYAFh1ilc=,tag:MM+YDRYCPuLvqpkPtJzCcw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:rmuUPy1TZSK9qz33EmUQD/f6BkFv7STVYfD1QN5zlJUifVlCjqlYkex2YDeQUDnSzJzBBQincuuGzu+WK92pV1mLWRG0mbwJ9ir3BDRB/o3Npoc5OVb8ZA==,iv:l0S3W/fHp2mKQk4xSx2XP+JK57so4fFzvmJLvfE7fMs=,tag:e4b+jonn/iBu0p1Uw+civA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZa0ZxYUVkLzJEVFg4WEYw
            TG5EK2tFZ3Z1bWhkR24zVGl0cG9KWXExTWhRCk5SNlNrTGVOeTZXUHlSNlNxS0Q2
            Q09kbDlzZzY0bStVS3A2SThEZFN3bVkKLS0tIG5selFuVEJTUVdvWm56aS92R283
            S0JndVdpUnVvK25Wa2VjMVNUdzg2aXcKDjq/7bM0sP+uH2j5XDFZIqwQ49VwZdfx
            28VDaLYfgghfn+eW9LzzhXqpAuUN5wpeUjqLTrmm1a3CUW0Cqb9QFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0gyKzBFT1laM0pzcWJG
            V2JSemsybXZlaHBKZmRmeFpGdEFhS2FmNEYwCmZvWFl2VmNJaHRhR2IxajdHdmd3
            VU51dVNRTFp2cTIySUN6ekJXaDdKa2MKLS0tIG01cjIyU05yNXhUV2hvWFNMODYv
            NDU3OXdHOENIOEJET0xLOEFsRWJRL2sKSG8+t/QRPufg7eYfp2YT5oOXZ/aIMnCY
            0De8xiF6KaLYCA5kPihHa0TEcVXrnjuCZhEM61GPYoKt5GgdhAy4dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T21:32:17Z"
    mac: ENC[AES256_GCM,data:YzFzgctJWgSDlpAzxmx8NsFXCiQGKPUnnQshMhyEl7OTscpBZQ+TjtVQHwKIwyddF49osbE2MFlZ4JnF6fMbBcJQJzonVN0mkDyMUegOpCaez3fxaLg4hWN79Cn6gjv4fQEY93lpDlE6rRTRKgHQU2Yl3zqcWawqOcWQtstQcjY=,iv:p5Yazl7VlDQrFkRJOlv40ZpKnvHf6U4gWeozpOHtI0M=,tag:xuC28943p+Nvt088wWU0Uw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:8vtrvZV3HnY=,iv:QV+od53/kXqGOvBEJ/EDJvQaDQLm6TLY62xwTnu9eNE=,tag:I1RI5AUcjcZeLpI9OTYdLw==,type:str]
    password: ENC[AES256_GCM,data:s20UWc5HlJiPFzmYohVWhzx1pFslMP2PYA==,iv:oE0LS5uKILA+oszl73iXGoKn4utLf0a5O6HdYXTQ3gY=,tag:ltq09A7sj1dETY8k3Up9qQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZa0ZxYUVkLzJEVFg4WEYw
            TG5EK2tFZ3Z1bWhkR24zVGl0cG9KWXExTWhRCk5SNlNrTGVOeTZXUHlSNlNxS0Q2
            Q09kbDlzZzY0bStVS3A2SThEZFN3bVkKLS0tIG5selFuVEJTUVdvWm56aS92R283
            S0JndVdpUnVvK25Wa2VjMVNUdzg2aXcKDjq/7bM0sP+uH2j5XDFZIqwQ49VwZdfx
            28VDaLYfgghfn+eW9LzzhXqpAuUN5wpeUjqLTrmm1a3CUW0Cqb9QFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0gyKzBFT1laM0pzcWJG
            V2JSemsybXZlaHBKZmRmeFpGdEFhS2FmNEYwCmZvWFl2VmNJaHRhR2IxajdHdmd3
            VU51dVNRTFp2cTIySUN6ekJXaDdKa2MKLS0tIG01cjIyU05yNXhUV2hvWFNMODYv
            NDU3OXdHOENIOEJET0xLOEFsRWJRL2sKSG8+t/QRPufg7eYfp2YT5oOXZ/aIMnCY
            0De8xiF6KaLYCA5kPihHa0TEcVXrnjuCZhEM61GPYoKt5GgdhAy4dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T21:32:17Z"
    mac: ENC[AES256_GCM,data:YzFzgctJWgSDlpAzxmx8NsFXCiQGKPUnnQshMhyEl7OTscpBZQ+TjtVQHwKIwyddF49osbE2MFlZ4JnF6fMbBcJQJzonVN0mkDyMUegOpCaez3fxaLg4hWN79Cn6gjv4fQEY93lpDlE6rRTRKgHQU2Yl3zqcWawqOcWQtstQcjY=,iv:p5Yazl7VlDQrFkRJOlv40ZpKnvHf6U4gWeozpOHtI0M=,tag:xuC28943p+Nvt088wWU0Uw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-backup-s3
type: Opaque
stringData:
    accessKeyId: ENC[AES256_GCM,data:7ySLGxESH6S/UxoQbBlCM55aJmKEiA1WYywQ/+LFgIo=,iv:/IIugYHK8e0YdaW49fx/V0GcsOnJ++R0ruLBwYMN/Kc=,tag:+eOPc9aLhLE8c+oHv9Wcjg==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:bW/bDIt5VGAY8wSyGjiKT4dR8B0mtpKZydewme4qDnk6mIe7U/03UsvsovZWdSsPEtcSI4S9HUAlSIqW7FC6fQ==,iv:WWIsMKjWxb1x3k2lOKfSEmdMiQkvKJhAGBual48aX5k=,tag:0jVTZ5Vxs7mGBCCoR82pzA==,type:str]
    endpoint: ENC[AES256_GCM,data:LLWxUGbh7iYZrVEUyHX3MBoPOT5uYeAgtA2xNb6Hibb7uuYwujWm3TJFjdCzOSB6LraxZ98tdyijl3DYBG6cfRp6Pf9x86fwZgOvMIEZGw==,iv:saSq8qOhxAx0w+hB5j5fUEN9/FPMVAfOBPLzReI8E5A=,tag:2OB+axGibdvJLotfB8R9UA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZa0ZxYUVkLzJEVFg4WEYw
            TG5EK2tFZ3Z1bWhkR24zVGl0cG9KWXExTWhRCk5SNlNrTGVOeTZXUHlSNlNxS0Q2
            Q09kbDlzZzY0bStVS3A2SThEZFN3bVkKLS0tIG5selFuVEJTUVdvWm56aS92R283
            S0JndVdpUnVvK25Wa2VjMVNUdzg2aXcKDjq/7bM0sP+uH2j5XDFZIqwQ49VwZdfx
            28VDaLYfgghfn+eW9LzzhXqpAuUN5wpeUjqLTrmm1a3CUW0Cqb9QFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0gyKzBFT1laM0pzcWJG
            V2JSemsybXZlaHBKZmRmeFpGdEFhS2FmNEYwCmZvWFl2VmNJaHRhR2IxajdHdmd3
            VU51dVNRTFp2cTIySUN6ekJXaDdKa2MKLS0tIG01cjIyU05yNXhUV2hvWFNMODYv
            NDU3OXdHOENIOEJET0xLOEFsRWJRL2sKSG8+t/QRPufg7eYfp2YT5oOXZ/aIMnCY
            0De8xiF6KaLYCA5kPihHa0TEcVXrnjuCZhEM61GPYoKt5GgdhAy4dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-20T21:32:17Z"
    mac: ENC[AES256_GCM,data:YzFzgctJWgSDlpAzxmx8NsFXCiQGKPUnnQshMhyEl7OTscpBZQ+TjtVQHwKIwyddF49osbE2MFlZ4JnF6fMbBcJQJzonVN0mkDyMUegOpCaez3fxaLg4hWN79Cn6gjv4fQEY93lpDlE6rRTRKgHQU2Yl3zqcWawqOcWQtstQcjY=,iv:p5Yazl7VlDQrFkRJOlv40ZpKnvHf6U4gWeozpOHtI0M=,tag:xuC28943p+Nvt088wWU0Uw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
