resources:
  - deployment.yaml
  - redis.yaml
  - pg.yaml
  - pvc.yaml
  - ingress.yaml
  - secret.yaml
  - image-upgrader.yaml
namespace: outline
images:
  - name: outlinewiki/outline
    newTag: 1.9.2 # {"$imagepolicy": "outline:outline:tag"}
