apiVersion: v1
kind: Secret
metadata:
    name: outline-env
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:IS/Bfnh+yA/Z8G5YlpAEwWdzlVXoXlqRrSPIZcjJfcFO3a4R6X1enA4eGpWAmCmzEzErJtrajYEjseV1WsbFEg==,iv:qyISKF4hxw3azcyvjzddvcEJfBeLs7tKrVE47j9gOOE=,tag:yiQFquagbtLCe0f7g886Jg==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:D3No+kNqAHqOtkre4h0WwEUYnIIlGUg7qd7AIKKOrd2TESeB2ho9ybI3hJY08momSu0LnKNUCSL9U/KaL9HczA==,iv:JwOwNGcT1ESc8Qz7jLOGSgEd62sfk55kvRYkAXqwoh0=,tag:4C0s0Am48m+w97tdbl/1vA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:yS7KVIqjkT6f6L6+nN84e2Mq1oeVoiwMLeL0XdS8q6TtJnvPTYWIUtAv6vQ1Qo11ybKPFnVzS3JgDocHU+o+rddG7nuiKcTmIF5QURfZ,iv:xzr6NmNvWkkqZhyNtHqwHGhTVFsTTbpLfg5QzW+mCMA=,tag:ntIs+a2EYKqOXHohFltHkg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:5nBt7ol95LzD33sSsQOXO8gXPMlbkvKb+j03VxC+ksQ=,iv:Qwp8egxFGsLZKmxRai8Jvyc0drv1ur66vJ9dxLuMQWM=,tag:OIWvWWpCnYVnbicJngsV0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTCtNU2RtYXc2OGRKSzdO
            UjA4bEF0UXVWeWFaRXBLZmUydWJCZ1M0TlFZCjNKMDNmbmxtdW85V01PL3VQYXBP
            N3pPTzMwZ2JxdjhITDN4WEhkUTlPb0kKLS0tIGlGT3Rpdkc5UGlEVm8vcmUxbmw1
            d2xNaHRNSGlwMTJJR3VJbitCUXhyc0UKi9yYKmKevIMMb6AUw+rB0Rrb6qS0O/qv
            w0P5XLRmVndU2SzmfLZm9cURboiUe9x4WMQ7YLW0KhYXKl3teO8zng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV3IyeSthZlN0a3k3NVp6
            eWhhR1dNck5yV0hPbFFyMUdoWFdraThkYlFJClNHVVhTcG1LcGpqOTQ2SmNuUzBm
            Nks4M0xoNlZBbUpIREQ4N0FrNkN3RHMKLS0tIG9RS3pyQmZScGg1eThOYXN3aWtz
            T3NDWlo4SStiMUNxT21Nbmh0MThWdlUKSvIqoRu2p0Bp8T+ZhB/tCs1zSKd0oo/o
            93tRZlntQGc+1KbE2vBkE+7eeMwFaTd2gyMctnKLH3nmFcZhx/DaFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g4q5q0lytudrnvvmdgxnlhwu37lak0qgk8kf4dahg4md87wj0ytq2l2xuc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a1BVdnFmWko4SWV6cDFo
            UkhPRFFPSURTOG1lblFuaVk4Nyt3MFV5VkZNCkRxTjR3bE9TaGpSNWJVVFI4V3F6
            bmdRTkxyUVNER0Y2WURxWmlwQk4zcWcKLS0tIFhEWUM5QVVFM25HY0xCaDdVVE1k
            MzNIOTdGdGl4Y1NWa0NqdWFtRUJMbFkKgqh9WYOt4v8IGIdTALM9eU/QJir+hGXL
            ZE0VM3OGEct08orIVwBkn6tQxMYmbIUf0MEsMcw4C+2VcTaBwKZgRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T13:13:57Z"
    mac: ENC[AES256_GCM,data:ecnYy5X9shoBM9KObkotQqxAj1VAbGd9vExGsGvuyld3I+EQoPnv4VF2AiPBo9BD/ZWQbeMkchNlP14OTcacdrfh75PjSFrSjtPO9Y+tYdWvHa0OhDXybU/ko/ynKVbp3dDuhGnhgdfDVPRLakZ9bfrPLV2SAqI36tAaAbL/L/o=,iv:WMpcKIerSri/1UVRkSj9yLbAM+C1ztZNMD3e2ocaOMk=,tag:FBSpRTkbLWhfzRYq9kvLSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: pg-credentials
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:/wP2flqzbQ==,iv:2SRq+ontZMdYr4QRREol831GLNCZi2HeOlhthr3HMdc=,tag:v3YTcpyQeS3hZ9YM3XqmAA==,type:str]
    password: ENC[AES256_GCM,data:1e/fQl9vIne2+KJOnuRTPnGPMZWwJ4aX8fwhCQUIsYs=,iv:Hf1MF4dxSkC3QWgaYKf7Gce6t2yAg/hHRKHzded/G4M=,tag:SY/z01iKv6869MztNrxnNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTCtNU2RtYXc2OGRKSzdO
            UjA4bEF0UXVWeWFaRXBLZmUydWJCZ1M0TlFZCjNKMDNmbmxtdW85V01PL3VQYXBP
            N3pPTzMwZ2JxdjhITDN4WEhkUTlPb0kKLS0tIGlGT3Rpdkc5UGlEVm8vcmUxbmw1
            d2xNaHRNSGlwMTJJR3VJbitCUXhyc0UKi9yYKmKevIMMb6AUw+rB0Rrb6qS0O/qv
            w0P5XLRmVndU2SzmfLZm9cURboiUe9x4WMQ7YLW0KhYXKl3teO8zng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV3IyeSthZlN0a3k3NVp6
            eWhhR1dNck5yV0hPbFFyMUdoWFdraThkYlFJClNHVVhTcG1LcGpqOTQ2SmNuUzBm
            Nks4M0xoNlZBbUpIREQ4N0FrNkN3RHMKLS0tIG9RS3pyQmZScGg1eThOYXN3aWtz
            T3NDWlo4SStiMUNxT21Nbmh0MThWdlUKSvIqoRu2p0Bp8T+ZhB/tCs1zSKd0oo/o
            93tRZlntQGc+1KbE2vBkE+7eeMwFaTd2gyMctnKLH3nmFcZhx/DaFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g4q5q0lytudrnvvmdgxnlhwu37lak0qgk8kf4dahg4md87wj0ytq2l2xuc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a1BVdnFmWko4SWV6cDFo
            UkhPRFFPSURTOG1lblFuaVk4Nyt3MFV5VkZNCkRxTjR3bE9TaGpSNWJVVFI4V3F6
            bmdRTkxyUVNER0Y2WURxWmlwQk4zcWcKLS0tIFhEWUM5QVVFM25HY0xCaDdVVE1k
            MzNIOTdGdGl4Y1NWa0NqdWFtRUJMbFkKgqh9WYOt4v8IGIdTALM9eU/QJir+hGXL
            ZE0VM3OGEct08orIVwBkn6tQxMYmbIUf0MEsMcw4C+2VcTaBwKZgRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T13:13:57Z"
    mac: ENC[AES256_GCM,data:ecnYy5X9shoBM9KObkotQqxAj1VAbGd9vExGsGvuyld3I+EQoPnv4VF2AiPBo9BD/ZWQbeMkchNlP14OTcacdrfh75PjSFrSjtPO9Y+tYdWvHa0OhDXybU/ko/ynKVbp3dDuhGnhgdfDVPRLakZ9bfrPLV2SAqI36tAaAbL/L/o=,iv:WMpcKIerSri/1UVRkSj9yLbAM+C1ztZNMD3e2ocaOMk=,tag:FBSpRTkbLWhfzRYq9kvLSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
