apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alloy-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/riko/apps/alloy/secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: alloy
