apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-s3-secret
  namespace: flux-system
spec:
  targetNamespace: csi-s3
  interval: 10m0s
  path: ./clusters/riko/core/csi-s3/secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
