apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:cMsJN5TpuMeEWkN6zToY5zcbHx9zOl2I2qDiS2AeKyx6j1W8pfG2AMeVAZQ=,iv:tqxdLLOd8Ve5Gpp5aMKKAJoKcJSUq2g+n/XZ83Gqz2Q=,tag:Qx2POdCIgR2dpFws1sCOAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMREJ4U2ptekFCV2RRM3Ey
            R2dJd2Ixc2o2V3JnWExLUXorVExMNFFKWm5ZCmFxamhvbVRZaEJLeFJ0VnFBdU4x
            ZW9KVTlGd096ZE5mZEV4cDVFcGQxbG8KLS0tIEUwZkgwaHgyK2lNQy9ETEFiak16
            T2hTN3hBOHVsQW9ZUzhHYUZpWEVreUkKpDXFiyd+JUplqaFUIoR1txrfy9FflQkF
            uTlszRQ6ul5cBO1+9O58HOJP3tyf7/J5vdreTiTYQUt/5iMNiPpTkA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcEttY3luU29DeDNRVGFq
            QkppQ2hmVEZ6eHVGaU1zeDZCeTdkYnh6L2hZCldFejdUc3BHeDJiMnVmRWtlVXJt
            UUNtMnBhT1dMcVVlRXlzaTFhazI5bVUKLS0tIEQ4OHhBTXA4Z0lobGV5WHkrZHlw
            WXU1NUNWbmFjY3U1aWdwNW82WXBkVWsKr1TiAS+EKjKPAYV5gC+m1iRHhq4ORQfA
            1AQj8zAv+k+z2VmBYYfChcJ4sazuYYjo2Fy5FOR2C/tfhEcsCNsQYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g4q5q0lytudrnvvmdgxnlhwu37lak0qgk8kf4dahg4md87wj0ytq2l2xuc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbnpiN2NDbkpvdnE4T3M0
            cmFPbjVBOWY4eE5ySFNVcEhIYmNrdDFQWmc0CkV0RTVDMHZBalZDaFE4WDJIbnp0
            dDA2SkpCaGkzNitVbzY3UmY3c2lVNW8KLS0tIG50MGRUMXBqMEZ6NXFpWHFSQXdP
            ZEJ1T2lVMGxyZDB5MitHenhTM2JWeUEKBZAPxMstnwvuEAy3EilHOiDoCjWTGoUq
            qq3ku24/XDEjhp01SRJ6qgj8szGb5jk2s0sOgnzYq2As5Mt6SfAnfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T12:56:03Z"
    mac: ENC[AES256_GCM,data:7ccE8ityDkBwIsIZW43SekNy1oPkHtuka2Dlk+sbjH24pFhSfeONs52MXH6wNuqq7x6Z3mjfhuZ77yWqYlTQ9du3q2sCdoXiQgkqFaayEPf4GpotToD1oBYKI225wwovcXgNUcUvVA2bRlYHMdhkynIvh0UlpyJKYuoDOeMWGQo=,iv:rWWVlll3DiSWBqti1C4lwHqIjIyXTSJqUJgtmd94FOc=,tag:u6euh+EE2NZuh0KZJmDyBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
