apiVersion: v1
kind: Secret
metadata:
    name: flux-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:evn9MpVWtnp1D9LBhFHZcgRzj/LDdnO6PQrKuanPiUWtvu+hHKk2EA/IobWvzMGts0G7X596f5Y+wIP0FLdS1w==,iv:Cd+ruaNrtRzH9dZbIrqEAydp469Irq0r3BNSp74+XzY=,tag:RuysaAuT7zXpVwhnvynDjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMVF6bzM1YU0yTk1DMGMw
            NmxVODN0NkpENWNmdlZ3blBzMkl4Rk5BdEQwCnlxS0Z1bC9xVU03aW8ydlZLVXNS
            TkxCZUttT0R5Z24wdXlnYVJQdGUrbmsKLS0tIDdQZktkaDNsdVZnWm1iMEMzMFd4
            b1ZTMGZPMVZ2eTAwSW9saTRkeTk0RVkKNTnA+8DgVaztfbdO7g9jGIBHIX3YUlg/
            KS9RQGuVFf1iDSvlaxTTr3roz1UT+IKcjzw0jeEt0CBgsYJWHZwTzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OG1tMXhsWlNSUlVLdkJU
            MXlhdjV5NFJudFNvYlJYT21zaDd1Wlh2eXl3CmYwTjcvNk12czlmYzc1ZXZBdmQy
            bXRtNllWV253Z0RXb0dzVm1tWUl6STAKLS0tIE9ydzIvZDRaQm5FSjcxb0ZKdXZL
            ZG1zeTFYRnQ0cmpLeEVNK05lWnI5QW8KDyoVNQm1stiCDR+SJNCYEzNo2P3fohti
            P3Da2Mew8W1qugZEEVYh+nuIjWxVt9fSl6elrnpIhbOMxuW+6YiXTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbjZyNkJndmlmOUtmdUVT
            b1pFTVFmcVczV0Vyb1R5ejB2RVZHZ2xkdmtRCjVKTGdlakJUNHpoamsvTDRYZ21K
            Ym1mTTFxTkc3QmtSZGpXeG1zYTF6alUKLS0tIEZZakEzT0hxVWMxSVdJbEtUaGlr
            NG4xOTRicDBObVFnY3BBL3ZSZDkvZmMK4dEYKQGmcO2tK+bCFqbSfVZ3li44kgER
            EHtOj/lDS9PHGciiGWsnfq8p2ny3jmHHVJ0UpLCk26XjsLMc5/OdWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4q5q0lytudrnvvmdgxnlhwu37lak0qgk8kf4dahg4md87wj0ytq2l2xuc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:16:02Z"
    mac: ENC[AES256_GCM,data:sfMNn0MrieawDGaYer/S0uplK+sJalE0j5gvQQ7Vw9cPonyAi7Y6TWlF7KAfM7gRX0pQdThSiO1iK+z7k3GaAxtQsglDoCUhOBkCSgOr7HgSVQGWJ7rNj2q33I3a3ZNN4dQIUBRWP21agCpjYo7rMizti+ZJqbnubw74gE+abgA=,iv:ubeLENm2aXbIQHwjCt+C32SEPMOZ+Ahrogk5vuIix0w=,tag:VN8D+Use4R1wkINL8fGbKQ==,type:str]
    version: 3.13.3
