apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: waifubot
  namespace: flux-system
spec:
  type: generic
  secretRef:
    name: flux-webhook-token
  resources:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: flux-system
      namespace: flux-system
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImageRepository
      name: waifubot
      namespace: waifubot
