apiVersion: v1
kind: Secret
metadata:
    name: grafana-alerts
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:4TlsGX8kA9xeFa8oRytLtV3JOwE08AXNGAgz8MWUOpyPCf3Q3XB5wwVkL/5hOA==,iv:V8mkUqvkLdVODKt+eheOLUqsQbYkd9j9hr+XzAqDBj4=,tag:2ngp3EYVWSQZuV0QqGJodw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL2tWMlRKNEoyZ3paNURU
            T1hCc2JlN3c2NVpzUWc2MjVVTGlhMHYvbFh3ClVsZjVua0xuZDRxcHBGRXplSTNO
            ZDRjenU4WDdQeVFwVmk5U2hVWnJQalEKLS0tIFFPRHRlN1ROVXdQUUZmRUY2bnVN
            bUxjVTh4d25sTXpmWU94aEtuc3FHczAK1Ce0GGROBc6mgvV2AaLoxaEQ8a6sA/nT
            gfr6AxgtmYuJIyR/Wc7KAj+JP8e5Noe2w2RdxDL0ryl7tAX0dQ6DZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age189p4fntprw5aj5ss9ze9yz6jxxypylhxthwr7pnqjusfw2xl6cuqdj3lse
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ2VXYUNPN2d4U1BIU2Va
            VlVPQTVqb2VxSUhSNmNBVjFXaW5SMDl1M1g4CngwMEJ4QWdUNHgzN0NaQVVFbjZj
            V0Fyc1dhZnYxVGlWVW9HZjVIdC9qcncKLS0tIFNkaTFvZE1PRDYzeDlRSEJKY21i
            NGNLSkN0cTVTM3M3QkFrdnhOdGVjeTAKYPkPAuP34uMkv1o8oy69pE/SXRlq8aCk
            vwvNbtdMM60T/T+epI29GjcPxcLp0EgvsgCafsYQUFg0/M2AvbwFzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5g3e2kl2kmrxdjlwzl884dhjlfz07jsulhfrdttme56dh45k3rspeka7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL2pST0h2d3RLOW42ZEhX
            WUVPQWROSkxKU1BQVHpRYzI1YThJMkM0SWlnCjgzM29oT1dsZ1R5dTM1cDk0aUN1
            RTNtdUp4TjJpbkk2WGVyTWhrQkNTZ00KLS0tIEhxQ0lxK3ZBUC95OFJRcllPRFdS
            b3JydWtVemxvMGNySjJkaE1QaVo2eFUKrW3Gf4+EjGew+nPiC6MQy7u7+cCKh07u
            lq3Rhu2yChbj277d8VpM+QgW6l4Y58AQIsw6/y0pzSngdT1FBj981Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4q5q0lytudrnvvmdgxnlhwu37lak0qgk8kf4dahg4md87wj0ytq2l2xuc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T16:49:30Z"
    mac: ENC[AES256_GCM,data:du/TC4koGlinoFBfuaXQZeDJsJHtKkWcqSEzI35YH9P4Cpogt6XZhUZhAYP6zQoK+MqFu0WNxga+ehN4PjKP+WWfL3c8QN4ZoX7wkpbFNkb32Dad89oJfws/aLaHeKgg9ZE8mUYDqu+aj72aZ9NADXy9iVLcNrhtm12zMeZ7tjo=,iv:Op+5x24/A8iNfG6jQkl8YA/yqSgouKambNaJRvndacg=,tag:TRJJZcuvO9NzFoGp+ItGYw==,type:str]
    version: 3.13.1
