apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: waifubot
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: waifubot
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/waifubot
  prune: true
