apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: klum
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/jadolg/klum
  ref:
    tag: v0.8.1
  ignore: |
    # exclude all
    /*
    # include deploy.yaml
    !/deploy.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: klum
  namespace: klum
spec:
  targetNamespace: klum
  interval: 12h
  prune: false
  sourceRef:
    kind: GitRepository
    name: klum
    namespace: flux-system
  patches:
    - target:
        kind: Deployment
        name: klum
      patch: |
        - op: replace
          path: /spec/template/spec/containers/0/env
          value:
            - name: CONTEXT_NAME
              value: riko
            - name: SERVER_NAME
              value: https://k1.k8s.0xf.fr:6443
            - name: NAMESPACE
              value: klum
            - name: DEFAULT_CLUSTER_ROLE
              value: "cluster-admin"
