apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: klum-users
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/klum/users
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: klum
  dependsOn:
    - name: klum
