apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: opencode
spec:
  image: ghcr.io/anomalyco/opencode
  interval: 15m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: opencode
spec:
  imageRepositoryRef:
    name: opencode
  policy:
    semver:
      range: 2.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: opencode
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "apps/opencode: {{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}"
    push:
      branch: main
  update:
    path: ./apps/opencode
