apiVersion: v1
kind: Service
metadata:
  labels:
    service: mc-survivor
  name: mc-survivor
spec:
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 30566
  selector:
    app: mc-survivor
  type: NodePort
