apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: attic-tls
spec:
  secretName: attic-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - nix-cache.karitham.dev
