apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: attic-pg
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4
  storage:
    size: 2Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: attic
      owner: attic
      secret:
        name: pg-credentials
